#!/usr/bin/env python3
"""Derive a manual, artifact-only build from the pinned upstream 1.4.9 workflow.

Development dependency: PyYAML==6.0.2. Run from any working directory.
Keep upstream workflows intact so future upgrades can be compared directly.
"""
import copy
from pathlib import Path
import re
import yaml

ROOT = Path(__file__).resolve().parents[2]
WORKFLOWS = ROOT / ".github/workflows"


class Loader(yaml.SafeLoader):
    pass


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def represent_string(dumper, value):
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|" if "\n" in value else None)


Dumper.add_representer(str, represent_string)


# GitHub uses YAML 1.2: a matrix key named `on` is not a boolean.
Loader.yaml_implicit_resolvers = {
    key: [(tag, rx) for tag, rx in values if tag != "tag:yaml.org,2002:bool"]
    for key, values in Loader.yaml_implicit_resolvers.items()
}
Loader.add_implicit_resolver("tag:yaml.org,2002:bool", re.compile(r"^(?:true|false)$", re.I), list("tTfF"))

CHECKOUT = "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"
UPLOAD = "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
SERVER_ENV = {name: "${{ secrets." + name + " }}" for name in
              ["RENDEZVOUS_SERVER", "RS_PUB_KEY", "RELAY_SERVER", "API_SERVER"]}
PREPARE = {
    "name": "Embed Visual Software server settings",
    "shell": "bash",
    "run": "python3 tools/visual-software/configure_server.py",
}
SELECTED_JOBS = [
    "generate-bridge", "build-RustDeskTempTopMostWindow", "build-for-windows-flutter",
    "build-for-macOS", "build-rustdesk-android", "build-rustdesk-android-universal",
    "build-rustdesk-linux", "build-appimage",
]


def add_config_step(job):
    steps = job.get("steps", [])
    for index, step in enumerate(steps):
        if str(step.get("uses", "")).startswith("actions/checkout@"):
            steps.insert(index + 1, copy.deepcopy(PREPARE))
            return
    if steps:
        raise ValueError("Build job has no source checkout")


def write(name, data):
    (WORKFLOWS / name).write_text(
        "# Generated by tools/visual-software/generate_workflow.py; upstream 1.4.9.\n"
        + yaml.dump(data, Dumper=Dumper, sort_keys=False, width=120, allow_unicode=True), encoding="utf-8")


def main():
    upstream = yaml.load((WORKFLOWS / "flutter-build.yml").read_text(), Loader=Loader)
    workflow = {
        "name": "Visual Software — Windows, Linux, macOS, Android",
        "on": {"workflow_dispatch": {}},
        "permissions": {"contents": "read"},
        "concurrency": {"group": "visual-software-${{ github.ref }}", "cancel-in-progress": False},
        "env": copy.deepcopy(upstream["env"]),
        "jobs": {},
    }
    workflow["env"].update(SERVER_ENV)
    workflow["env"].update({"UPLOAD_ARTIFACT": "true", "TAG_NAME": "visual-software-1.4.9"})
    workflow["jobs"]["validate-configuration"] = {
        "runs-on": "ubuntu-24.04",
        "steps": [
            {"uses": CHECKOUT},
            {"name": "Test public server configuration validation", "run": "python3 -m unittest discover -s tools/visual-software -p 'test_*.py'"},
            copy.deepcopy(PREPARE),
            {
                "name": "Check Android release signing credentials",
                "env": {k: "${{ secrets." + k + " }}" for k in [
                    "ANDROID_SIGNING_KEY", "ANDROID_ALIAS", "ANDROID_KEY_STORE_PASSWORD", "ANDROID_KEY_PASSWORD"]},
                "run": "python3 - <<'PY'\nimport os\nrequired = ['ANDROID_SIGNING_KEY', 'ANDROID_ALIAS', 'ANDROID_KEY_STORE_PASSWORD', 'ANDROID_KEY_PASSWORD']\nmissing = [k for k in required if not os.environ.get(k)]\nif missing:\n    print('Android signing secrets are incomplete; unsigned test APKs will be generated. Missing: ' + ', '.join(missing))\nelse:\n    print('Android signing configuration present; values hidden.')\nPY\n",
            },
        ],
    }
    for name in SELECTED_JOBS:
        job = copy.deepcopy(upstream["jobs"][name])
        workflow["jobs"][name] = job
        if name == "generate-bridge":
            job.update({"needs": ["validate-configuration"], "uses": "./.github/workflows/visual-software-bridge.yml", "secrets": "inherit"})
            continue
        if name == "build-RustDeskTempTopMostWindow":
            job["needs"] = ["validate-configuration"]
            job["with"]["upload-artifact"] = True
            continue
        job.pop("if", None)
        add_config_step(job)
        for index, step in enumerate(job["steps"]):
            condition = step.get("if", "")
            if isinstance(condition, str) and condition:
                step["if"] = condition.replace("inputs.upload-artifact", "true")
                step["if"] = step["if"].replace("env.ANDROID_SIGNING_KEY != null", "env.ANDROID_SIGNING_KEY != ''")
                step["if"] = step["if"].replace("env.ANDROID_SIGNING_KEY == null", "env.ANDROID_SIGNING_KEY == ''")
                if step["if"] in ("true", "${{ true }}"):
                    step.pop("if")
            if name == "build-rustdesk-android-universal" and step.get("name") == "Upload Artifacts":
                step["with"]["name"] = "rustdesk-${{ env.VERSION }}-universal.apk"
            if str(step.get("uses", "")).startswith("softprops/action-gh-release@"):
                files = step["with"]["files"]
                step["uses"] = UPLOAD
                step["name"] = "Save installer artifact (not published)"
                arch = "-${{ matrix.job.arch }}" if "strategy" in job else ""
                step["with"] = {
                    "name": f"visual-software-{name}{arch}-{index}",
                    "path": files, "if-no-files-found": "error", "retention-days": 14,
                }
            if step.get("name") == "Build msi":
                step["run"] = step["run"].replace("python preprocess.py --arp", 'python preprocess.py --manufacturer "Visual Software" --arp')
            # The upstream rename adds the architecture twice to unsigned DMGs.
            if name == "build-for-macOS" and step.get("name") == "Rename rustdesk":
                step["run"] = 'if [ -f "rustdesk-${{ env.VERSION }}.dmg" ]; then\n  mv "rustdesk-${{ env.VERSION }}.dmg" "rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}.dmg"\nfi\n'
        if name == "build-for-macOS":
            index = next(i for i,s in enumerate(job["steps"]) if s.get("name") == "create unsigned dmg")
            job["steps"].insert(index, {
                "name": "Prepare ad-hoc signature for local testing",
                "if": "env.MACOS_P12_BASE64 == ''",
                "run": 'cp flutter/macos/Runner/Release.entitlements /tmp/visualsoftware-test.entitlements\n/usr/libexec/PlistBuddy -c "Add :com.apple.security.cs.disable-library-validation bool true" /tmp/visualsoftware-test.entitlements\ncodesign --force --options runtime --sign - --entitlements /tmp/visualsoftware-test.entitlements flutter/build/macos/Build/Products/Release/RustDesk.app\ncodesign --verify --deep --strict flutter/build/macos/Build/Products/Release/RustDesk.app\n',
            })
    write("visual-software-build.yml", workflow)

    bridge = yaml.load((WORKFLOWS / "bridge.yml").read_text(), Loader=Loader)
    bridge["name"] = "Visual Software — Flutter bridge"
    bridge["env"].update(SERVER_ENV)
    for job in bridge["jobs"].values():
        add_config_step(job)
    write("visual-software-bridge.yml", bridge)


if __name__ == "__main__":
    main()
